<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MBtecZfEmailObfuscator\Module' => __DIR__ . '/Module.php',
    'MBtecZfEmailObfuscator\View\Helper\EmailObfuscator' => __DIR__ . '/src/EmailObfuscator/View/Helper/EmailObfuscator.php',
);
